"""initial: all 15 tables

Revision ID: 7028cdccb5c0
Revises: 
Create Date: 2026-07-30 22:00:14.659862
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7028cdccb5c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('connection_details', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('scan_mode', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_reviews',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('team_lead', sa.String(), nullable=True),
    sa.Column('repository_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_audit',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('response_confidence', sa.String(length=20), nullable=True),
    sa.Column('response_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('cr_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_cr_number'), 'change_requests', ['cr_number'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('document_id', sa.CHAR(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chroma_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chroma_id'), 'document_chunks', ['chroma_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_id', sa.CHAR(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('documents_discovered', sa.Integer(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('documents_indexed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_aliases',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'alias', name='uq_project_alias')
    )
    op.create_table('project_documents',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('document_id', sa.CHAR(length=36), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_id', name='uq_project_document')
    )
    op.create_table('requirements',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_requirement_id'), 'requirements', ['requirement_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_id', sa.CHAR(length=36), nullable=False),
    sa.Column('document_id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_links',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.CHAR(length=36), nullable=False),
    sa.Column('chunk_id', sa.CHAR(length=36), nullable=False),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_artifacts',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('artifact_id', sa.CHAR(length=36), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'artifact_id', name='uq_project_artifact')
    )
    op.create_table('project_change_requests',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('change_request_id', sa.CHAR(length=36), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'change_request_id', name='uq_project_cr')
    )
    op.create_table('project_requirements',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('requirement_id', sa.CHAR(length=36), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'requirement_id', name='uq_project_requirement')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_requirements')
    op.drop_table('project_change_requests')
    op.drop_table('project_artifacts')
    op.drop_table('evidence_links')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_requirements_requirement_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('project_documents')
    op.drop_table('project_aliases')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chroma_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_change_requests_cr_number'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_table('artifacts')
    op.drop_table('query_audit')
    op.drop_table('projects')
    op.drop_table('metadata_reviews')
    op.drop_table('documents')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
